spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/syncria_db
    username: syncria_user
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
