spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/syncria_db
    username: syncria_user
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

app:
  jwt:
    secret: ZGV2LW9ubHktand0LXNlY3JldC1mb3ItbG9jYWwtZGV2ZWxvcG1lbnQtcHVycG9zZXMtb25seQ==
    expiration-ms: 86400000
